version: '3'

tasks:
  all:
    - task: nvim
  nvim:
    env:
      NVIM_VERSION: 0.10.1
    dir: '${HOME}'
    cmds:
       - wget https://github.com/neovim/neovim/releases/download/v$NVIM_VERSION/nvim.appimage
       - wget https://github.com/neovim/neovim/releases/download/v$NVIM_VERSION/nvim.appimage.sha256sum
       - sha256sum -c nvim.appimage.sha256sum
       - rm nvim.appimage.sha256sum
       - chmod u+x nvim.appimage
       - mkdir -p ~/.local/bin
       - mv nvim.appimage ~/.local/bin/nvim
       - nvim --version
  tmux:
    env:
      TMUX_VERSION: 3.5a
    dir: '${HOME}'
    cmds:
     - |
      sudo apt-get install libevent-dev ncurses-dev build-essential bison pkg-config automake
      git clone https://github.com/tmux/tmux.git || true
      cd tmux
      git fetch
      git checkout $TMUX_VERSION
      sh autogen.sh
      ./configure
      make && sudo make install
      tmux -V

    #TODO add these:
    # cmake https://askubuntu.com/a/865294/1195630

    # timewarrior https://github.com/GothenburgBitFactory/timewarrior?tab=readme-ov-file#building-timewarrior
    # sudo apt-get install asciidoctor
