#!/usr/bin/env bash
fd --ignore-file="$HOME/.fdprojectignore" -I -H -t d "\.git$" "$DOTFILES_GIT_REPOS_DIR" | sed -e 's|/\.git/*$||' | fzf --header='git projects' --header-first --preview "tree -C -L 1 --dirsfirst {}" --tmux
