#!/usr/bin/env bash

project=$(gitprojectfind)

if [ -z "$project" ]; then
    exit 0
fi

sessari="$(basename "$project")"
sessari_cleaned="${sessari/./_}"
if ! tmux has-session -t="$sessari_cleaned" 2> /dev/null; then
    tmux new-session -ds "$sessari_cleaned" -c "$project"
fi

tmux switch-client -t "$sessari_cleaned"

